import { Arrow, PageShell, Status } from "../components";
import InteractiveCore from "../interactive-core";

export default function CyberPage(){return <PageShell>
<section className="pageHero shell"><div><Status tone="cyan">CYBERSECURITY</Status><h1>SEE MORE. DEFEND EARLIER.</h1></div><div className="heroSide"><p>Cybersecurity applications and future defensive hardware designed to improve visibility, monitor networks, detect threats and support authorized security testing.</p></div></section>
<section className="contentGrid shell"><div><p className="eyebrow">CYBER / 02</p><h2>Defensive systems with real-world purpose.</h2><p>We are designing security technology around detection, telemetry, resilience and controlled testing—not unauthorized intrusion.</p></div><InteractiveCore variant="cyan"/></section>
<section className="contentGrid shell"><div><p className="eyebrow">SOFTWARE</p><h2>Security applications.</h2></div><div className="cardGrid"><article><span>01</span><h3>Network Defense</h3><p>Visibility, monitoring and defensive control surfaces for connected environments.</p></article><article><span>02</span><h3>Threat Detection</h3><p>Signal collection and intelligent detection workflows for suspicious activity.</p></article><article><span>03</span><h3>Security Monitoring</h3><p>Operational dashboards and event intelligence for continuous awareness.</p></article><article><span>04</span><h3>Authorized Testing</h3><p>Technology designed to support legitimate, permission-based security validation.</p></article></div></section>
<section className="contentGrid shell"><div><Status>HARDWARE DEVELOPMENT</Status><h2>Security hardware is part of the roadmap.</h2></div><div><p>Future device concepts include portable defensive appliances, travel security gateways, USB security scanners, incident-response devices and IoT/OT monitoring systems.</p><div className="specTable"><div className="specRow"><span>Presentation</span><span>3D rotation, zoom and exploded component views</span></div><div className="specRow"><span>Product data</span><span>Specifications, development status and deployment context</span></div><div className="specRow"><span>Commerce</span><span>Buy or preorder only when a device is ready for market</span></div></div><a className="textCta" href="/technology">Explore our technology approach <Arrow/></a></div></section>
</PageShell>}
