import type { Metadata } from "next";
import "../home-refresh.css";
import "./palm.css";
import "./palm-refresh.css";
export const metadata:Metadata={title:"PalmPay | Future",description:"PalmPay is a future biometric identity and payment platform from The Boring Product.",alternates:{canonical:"/future"},openGraph:{url:"https://theboringproduct.com/future",title:"PalmPay | The Boring Product",description:"A future biometric identity and payment platform designed for palm-enabled checkout."}};
function BrandLogo(){return <span className="brandLogo" aria-label="The Boring Product"><span className="brandThe">THE</span><span className="brandBoring" aria-hidden="true"><span>B</span><span className="brandSolidO"/><span>RING</span></span><span className="brandBottom"><span className="brandLines" aria-hidden="true"/><span className="brandProduct">PRODUCT</span></span></span>}
const useCases=[["Retail Stores","Faster checkout without a card or phone.","retail"],["Transit & Mobility","Identity and payment for supported gates and kiosks.","transit"],["Hospitality","A seamless guest payment experience.","hospitality"],["Workplaces","Identity, access and payments in one flow.","workplace"],["Events & Venues","Cashless entry and purchases at participating venues.","events"]];
export default function FuturePage(){return <main className="palmPage">
<header className="nav shell newNav"><a className="brand brandMark" href="/"><BrandLogo/></a><nav className="navLinks"><div className="navDropdown"><a className="navDropdownTrigger" href="/products">Products <span>⌄</span></a><div className="navDropdownMenu"><a href="/products#digital">Digital</a><a href="/products#devices">Devices</a></div></div><a href="/future">Future</a><a href="/#technology">Technology</a><a href="/#about">About</a></nav><a className="ghostButton heroNavButton" href="#how-it-works">See How It Works</a></header>
<section className="palmHero shell"><div className="palmHeroCopy"><span className="futurePill">FUTURE DIGITAL PRODUCT</span><h1>Palm<span className="payGradient">Pay</span><span>Your hand is your wallet.</span></h1><p className="lede">A software platform concept for biometric identity and palm-enabled payments. Enroll once, link a payment method, then verify at participating palm-enabled merchants without reaching for a card or phone.</p><div className="palmActions"><a className="primaryButton primaryButtonRefresh" href="#how-it-works">See how it works →</a><a className="secondaryPalmButton" href="#architecture">Platform architecture</a></div><div className="benefitRow"><span>◉ <b>Secure</b><small>Biometric identity</small></span><span>ϟ <b>Instant</b><small>Fast authorization</small></span><span>▣ <b>Private</b><small>Tokenized credentials</small></span><span>◎ <b>Connected</b><small>Merchant-enabled network</small></span></div></div><div className="palmStage"><div className="scanHalo"/><div className="palmHand"><span className="finger f1"/><span className="finger f2"/><span className="finger f3"/><span className="finger f4"/><span className="thumb"/><span className="vein v1"/><span className="vein v2"/><span className="vein v3"/></div><div className="scanLine"/><div className="miniTerminal"><span>PalmPay</span><b>✓</b><strong>Payment Approved</strong><small>$28.50</small></div><span className="scanLabel">PALM SIGNATURE / ENCRYPTED MATCH</span></div></section>
<section className="palmFlow shell" id="how-it-works"><p className="sectionLabel">HOW PALMPAY WORKS</p><h2>Four steps from enrollment to checkout.</h2><div className="experienceSteps"><article><span>01</span><strong>Enroll</strong><p>Create an encrypted palm identity with explicit consent.</p></article><article><span>02</span><strong>Link</strong><p>Connect a tokenized Visa or Mastercard payment method through a supported processor.</p></article><article><span>03</span><strong>Verify</strong><p>Present your palm to supported recognition hardware with liveness checks.</p></article><article><span>04</span><strong>Pay</strong><p>The transaction is authorized through certified payment infrastructure.</p></article></div></section>
<section className="realLife shell"><div className="realLifeHead"><p className="sectionLabel">PALMPAY IN REAL LIFE</p><h2>One identity layer. Many places.</h2></div><div className="useCaseGrid">{useCases.map(([title,copy,type])=><article className={`useCaseCard ${type}`} key={title}><div className="useCaseVisual"><span className="usePalm">✋</span><span className="useReader">◫</span><span className="useGlow"/></div><div><strong>{title}</strong><p>{copy}</p></div></article>)}</div></section>
<section className="palmGrid shell"><div className="palmGridHeader"><div><p className="sectionLabel">THE SOFTWARE LAYER</p><h2>Identity, payment orchestration and merchant infrastructure.</h2></div><p>The platform is designed to connect palm-recognition hardware, encrypted biometric templates, customer wallets, merchant software, and certified payment processors without making the raw palm image itself a payment credential.</p></div><div className="palmFeatureGrid"><article className="palmFeature"><span>01 / IDENTITY</span><h3>Palm Identity API</h3><p>Enrollment, liveness status, confidence scoring, device trust and consent state.</p></article><article className="palmFeature"><span>02 / WALLET</span><h3>Customer wallet</h3><p>Tokenized payment methods, receipts, privacy controls and account recovery.</p></article><article className="palmFeature"><span>03 / PAYMENTS</span><h3>Payment orchestration</h3><p>Authorization, refunds, receipts, settlement visibility and processor integrations.</p></article><article className="palmFeature"><span>04 / MERCHANT</span><h3>Merchant platform</h3><p>Locations, readers, transactions, fraud rules, audit logs, roles and analytics.</p></article></div></section>
<section className="palmArchitecture shell" id="architecture"><p className="sectionLabel">PAYMENT INFRASTRUCTURE</p><h2>Designed to work with existing payment rails.</h2><p>PalmPay is envisioned as the biometric identity and authorization experience above certified payment infrastructure—not as a replacement for Visa, Mastercard or acquiring networks.</p><div className="railsStrip"><span>VISA <small>planned compatibility</small></span><span>Mastercard <small>planned compatibility</small></span><span>Processor APIs <small>certified partners</small></span><span>Tokenization <small>payment credentials</small></span><span>PCI scope <small>processor-led architecture</small></span></div><div className="archGrid"><article className="archCard"><h3>Palm Identity API</h3><p>Enrollment, matching, liveness, confidence scoring, device trust, and consent state.</p></article><article className="archCard"><h3>Payment Orchestration</h3><p>Tokenized methods, authorization requests, refunds, receipts, and processor integrations.</p></article><article className="archCard"><h3>Merchant Platform</h3><p>Locations, readers, customers, transactions, fraud rules, audit logs, analytics, and APIs.</p></article></div><div className="futureDisclaimer">Concept only. Planned Visa and Mastercard compatibility refers to processing eligible credentials through approved processors/acquirers and applicable card-network programs. PalmPay would require supported palm-recognition hardware and merchant integration.</div></section>
<section className="palmPrivacy shell"><div className="privacyGrid"><div><p className="sectionLabel">PRIVACY BY DESIGN</p><h2>Your palm should identify you—not become a photo stored forever.</h2><p>The intended architecture prioritizes encrypted biometric templates, tokenized payment credentials, explicit consent, revocation controls and deletion workflows.</p></div><div className="privacyList"><div>Encrypted biometric templates</div><div>Tokenized payment credentials</div><div>Consent and revocation records</div><div>Role-based merchant access</div><div>Audit logging and fraud controls</div><div>Biometric data deletion workflows</div></div></div></section>
<footer className="footer shell"><div><a className="brand brandMark footerBrand" href="/"><BrandLogo/></a><p>We build boring products that solve real problems.</p><div className="footerContact"><a href="mailto:hello@theboringproduct.com">hello@theboringproduct.com</a><span>4202 Gnarl Dr, Austin, TX 78731</span><a href="https://x.com/TheBoringProduct" target="_blank" rel="noreferrer">X / @TheBoringProduct</a></div></div><div className="footerLinks"><a href="/products">Products</a><a href="/future">Future</a><a href="/#technology">Technology</a><a href="/#about">About</a></div><p className="copyright">© 2026 The Boring Product.</p></footer>
</main>}
