import { Arrow, PageShell, Status } from "../components";
import InteractiveCore from "../interactive-core";

export default function PalmPayPage(){return <PageShell>
<section className="pageHero shell"><div><Status tone="violet">PALMPAY / PROTOTYPE</Status><h1>YOUR HAND IS YOUR WALLET.</h1></div><div className="heroSide"><p>PalmPay is our flagship exploration of biometric identity and next-generation payments: scan a palm, resolve an encrypted identity and authorize a transaction through a secure payment flow.</p></div></section>
<section className="contentGrid shell"><div><p className="eyebrow">PALMPAY / 03</p><h2>Identity without reaching for a device.</h2><p>The product concept centers on a premium, low-friction payment experience where the user’s palm becomes the interaction layer while sensitive identity data remains protected behind secure matching and authorization systems.</p></div><InteractiveCore variant="palm"/></section>
<section className="contentGrid shell"><div><p className="eyebrow">EXPERIENCE</p><h2>Scan. Match. Authorize.</h2></div><div className="cardGrid"><article><span>01</span><h3>Palm Scan</h3><p>A compatible sensor captures the characteristics needed for biometric matching.</p></article><article><span>02</span><h3>Encrypted Identity</h3><p>The system resolves the scan against a protected identity representation rather than exposing raw biometric data.</p></article><article><span>03</span><h3>Payment Intent</h3><p>The matched identity is connected to an approved payment method and transaction context.</p></article><article><span>04</span><h3>Authorization</h3><p>The transaction proceeds only after the required controls and authorization checks succeed.</p></article></div></section>
<section className="contentGrid shell"><div><Status>PROTOTYPE</Status><h2>Built as a future system, not a feature card.</h2></div><div><p>PalmPay is being presented as a major technology program inside The Boring Product ecosystem. The public site distinguishes the concept and development status from a commercially released payment service.</p><a className="textCta" href="/technology">Explore the technology stack <Arrow/></a></div></section>
</PageShell>}
