import type { Metadata } from "next";
import "../../home-refresh.css";

export const metadata: Metadata = { title: "Client Engagements", description: "Selected client engagement experience across public sector, enterprise, cybersecurity, AI, cloud, and transformation work.", alternates: { canonical: "/contracts/client-engagements" } };
function BrandLogo(){return <span className="brandLogo" aria-label="The Boring Product"><span className="brandThe">THE</span><span className="brandBoring" aria-hidden="true"><span>B</span><span className="brandSolidO"/><span>RING</span></span><span className="brandBottom"><span className="brandLines" aria-hidden="true"/><span className="brandProduct">PRODUCT</span></span></span>}
const engagements=[
{name:"Federal Maritime Commission",type:"Federal / Cybersecurity / Assessment",copy:"Security assessment, ATO readiness, evidence review, control-gap analysis, risk documentation, and current-state cybersecurity support delivered in a federal environment."},
{name:"PiTech Solutions",type:"Technology / Delivery Partner",copy:"Technology consulting and delivery support spanning cybersecurity, compliance, assessment activities, and client-facing execution."},
{name:"Massed Compute",type:"Cloud / Technology",copy:"Cloud and technology engagement support involving secure delivery, infrastructure considerations, and execution in modern computing environments."},
{name:"Bank of America",type:"Financial Services / Enterprise",copy:"Enterprise technology and agile delivery experience supporting large-scale, regulated environments with complex stakeholders, controls, and delivery expectations."},
{name:"Booz Allen Hamilton",type:"Federal Consulting / Enterprise",copy:"Consulting experience supporting mission-focused technology, cybersecurity, transformation, and delivery environments serving government and enterprise stakeholders."}
];
export default function ClientEngagementsPage(){return <main><header className="nav shell newNav"><a className="brand brandMark" href="/"><BrandLogo/></a><nav className="navLinks"><div className="navDropdown"><a className="navDropdownTrigger" href="/products">Products <span>⌄</span></a><div className="navDropdownMenu"><a href="/products/expensemargin">ExpenseMargin</a><a href="/products/jrt-community">Jordan Ranch &amp; Tamarron</a><a href="/products/processpilot-technologies">ProcessPilot Technologies</a></div></div><div className="navDropdown"><a className="navDropdownTrigger" href="/contracts">Contracts <span>⌄</span></a><div className="navDropdownMenu"><a href="/contracts/client-engagements">Client Engagement</a></div></div><a href="/future">Future</a><a href="/technology">Technology</a><a href="/about">About</a></nav><a className="ghostButton heroNavButton" href="/contracts">Back to Contracts</a></header>
<section className="statement shell productsIntro"><p className="sectionLabel">CLIENT ENGAGEMENT</p><div className="statementGrid"><h1 className="productsTitle">Selected experience. Real delivery.</h1><p>Representative client and partner environments where our experience has supported cybersecurity, technology delivery, compliance, cloud, transformation, and enterprise execution. Engagements may have been performed directly or through consulting and contracting partners.</p></div></section>
<section className="products shell"><div className="productGrid">{engagements.map((item,index)=><article className="productCard" key={item.name}><div className="productIndex">0{index+1}</div><div className="productMeta"><span>{item.type}</span></div><h3>{item.name}</h3><p>{item.copy}</p></article>)}</div></section>
<section className="statement shell"><p className="sectionLabel">WORK WITH US</p><div className="statementGrid"><h2>Need a delivery partner for your next engagement?</h2><div><p>Share the scope, solicitation, SOW, or delivery need and we will assess fit, timing, capabilities, and the best engagement model.</p><a className="primaryButton primaryButtonRefresh" href="mailto:hello@theboringproduct.com?subject=Client%20Engagement%20Opportunity">Discuss an engagement →</a></div></div></section>
<footer className="footer shell"><div><a className="brand brandMark footerBrand" href="/"><BrandLogo/></a><p>We build boring products that solve real problems.</p><div className="footerContact"><a href="mailto:hello@theboringproduct.com">hello@theboringproduct.com</a><span>4202 Gnarl Dr, Austin, TX 78731</span></div></div><div className="footerLinks"><a href="/products">Products</a><a href="/contracts">Contracts</a><a href="/contracts/client-engagements">Client Engagement</a><a href="/future">Future</a><a href="/technology">Technology</a><a href="/about">About</a></div><p className="copyright">© 2026 The Boring Product.</p></footer></main>}
