import { Arrow, PageShell, Status } from "../components";
import InteractiveCore from "../interactive-core";

export default function AIPage(){return <PageShell>
<section className="pageHero shell"><div><Status tone="violet">ARTIFICIAL INTELLIGENCE</Status><h1>INTELLIGENCE, BUILT TO ACT.</h1></div><div className="heroSide"><p>We build AI systems that move beyond chat: agentic applications, secure automation, operational intelligence and experimental systems designed to perform useful work.</p></div></section>
<section className="contentGrid shell"><div><p className="eyebrow">AI / 01</p><h2>Systems that think across workflows.</h2><p>Our AI work focuses on practical systems that can reason, retrieve context, use tools, coordinate tasks and operate inside clearly defined human controls.</p></div><InteractiveCore variant="violet"/></section>
<section className="contentGrid shell"><div><p className="eyebrow">CAPABILITIES</p><h2>What we build.</h2></div><div className="cardGrid"><article><span>01</span><h3>Agentic AI</h3><p>Multi-step AI systems that can orchestrate tools, workflows and structured actions.</p></article><article><span>02</span><h3>AI Security</h3><p>Controls, monitoring and guardrails designed around AI-enabled environments.</p></article><article><span>03</span><h3>Intelligent Automation</h3><p>Automation that combines rules, reasoning and human approval where it matters.</p></article><article><span>04</span><h3>AI Applications</h3><p>Purpose-built interfaces that turn advanced models into usable products.</p></article></div></section>
<section className="contentGrid shell"><div><Status>RESEARCH + PRODUCT DEVELOPMENT</Status><h2>From experiment to system.</h2></div><div><p>Products can move through research, prototype, private beta and live stages without pretending every experiment is already commercial. That lets us build visibly, test responsibly and promote systems only when they are ready.</p><a className="textCta" href="/products">View product ecosystem <Arrow/></a></div></section>
</PageShell>}
