import type { Metadata } from "next";
import "../home-refresh.css";

export const metadata: Metadata = {
  title: "Products",
  description: "Explore live digital products and shipped devices from The Boring Product.",
  alternates: { canonical: "/products" },
  openGraph: { url: "https://theboringproduct.com/products", title: "Products | The Boring Product", description: "Explore live digital products and shipped devices from The Boring Product." },
};
const digitalProducts = [{name:"ExpenseMargin",status:"LIVE",category:"Finance / Operations",description:"Margin intelligence for businesses. Track supplier pricing, invoice changes, and cost pressure before they erode profit.",href:"https://expensemargin.com",domain:"ExpenseMargin.com"},{name:"Jordan Ranch & Tamarron",status:"LIVE",category:"Community",description:"A private digital community for residents, local businesses, marketplace activity, neighborhood deals, and local discovery.",href:"https://jrt.community",domain:"JRT.community"}];
function Arrow(){return <span aria-hidden="true">↗</span>}
function BrandLogo(){return <span className="brandLogo" aria-label="The Boring Product"><span className="brandThe">THE</span><span className="brandBoring" aria-hidden="true"><span>B</span><span className="brandSolidO"/><span>RING</span></span><span className="brandBottom"><span className="brandLines" aria-hidden="true"/><span className="brandProduct">PRODUCT</span></span></span>}
export default function ProductsPage(){return <main>
<header className="nav shell newNav"><a className="brand brandMark" href="/"><BrandLogo/></a><nav className="navLinks" aria-label="Products navigation"><a href="#digital">Digital</a><a href="#devices">Devices</a><a href="/future">Future</a></nav><a className="ghostButton heroNavButton" href="/">Back home</a></header>
<section className="statement shell productsIntro"><p className="sectionLabel">PRODUCTS</p><div className="statementGrid"><h1 className="productsTitle">Built. Shipped. In use.</h1><p>We only list products that are live. Digital products are available now, and devices will appear here as they ship. Future concepts live separately in our Future section.</p></div></section>
<section className="products shell" id="digital"><div className="categoryHeader"><p className="sectionLabel">PRODUCTS / DIGITAL</p><h2>Digital</h2></div><div className="productGrid">{digitalProducts.map((product,index)=><article className="productCard" key={product.name}><div className="productIndex">0{index+1}</div><div className="productMeta"><span>{product.category}</span><span className="status statusLIVE">{product.status}</span></div><h3>{product.name}</h3><p>{product.description}</p><a href={product.href} target="_blank" rel="noreferrer" className="cardLink">{product.domain} <Arrow/></a></article>)}</div></section>
<section className="technology shell"><div className="techVisual" aria-hidden="true"><div className="gridPlane"/><div className="techCube cubeOne"/><div className="techCube cubeTwo"/><div className="techCube cubeThree"/></div><div className="techCopy"><p className="sectionLabel">DIGITAL / BUILT FOR WHAT&apos;S NEXT</p><h2>Digital products at the intersection of intelligence and utility.</h2><p>We use modern AI, automation, cloud infrastructure, security engineering, and data systems where they create real leverage.</p><div className="capabilities"><span>Artificial Intelligence</span><span>Cybersecurity</span><span>Automation</span><span>Cloud Infrastructure</span><span>Data Intelligence</span><span>Applied R&amp;D</span></div></div></section>
<section className="technology hardwareTechnology shell" id="devices"><div className="techCopy"><p className="sectionLabel">DEVICES / BUILT FOR THE PHYSICAL WORLD</p><h2>Devices engineered where intelligence meets the real world.</h2><p>We are building purpose-built devices, edge systems, intelligent sensors, and physical technology. Devices will be listed here once they are shipped.</p><div className="capabilities"><span>Connected Devices</span><span>Edge Computing</span><span>Embedded Systems</span><span>Intelligent Sensors</span><span>Device Security</span><span>Device R&amp;D</span></div></div><div className="techVisual hardwareVisual" aria-hidden="true"><div className="gridPlane"/><div className="deviceShell"><div className="deviceCore"/><span className="devicePort portOne"/><span className="devicePort portTwo"/><span className="devicePort portThree"/></div></div></section>
<footer className="footer shell"><div><a className="brand brandMark footerBrand" href="/"><BrandLogo/></a><p>We build boring products that solve real problems.</p><div className="footerContact"><a href="mailto:info@theboringproduct.com">info@theboringproduct.com</a><span>4202 Gnarl Dr, Austin, TX 78731</span><a href="https://x.com/TheBoringProduct" target="_blank" rel="noreferrer">X / @TheBoringProduct</a></div></div><div className="footerLinks"><a href="#digital">Digital</a><a href="#devices">Devices</a><a href="/future">Future</a><a href="/">Home</a></div><p className="copyright">© 2026 The Boring Product.</p></footer>
</main>}
