import type { Metadata } from "next";
import { PageShell, Status } from "../components";

export const metadata: Metadata = { title: "Technology", description: "Technology foundations behind The Boring Product.", alternates: { canonical: "/technology" } };

export default function TechnologyPage(){return <PageShell>
<section className="pageHero shell"><div><p className="eyebrow">TECHNOLOGY</p><h1>SOFTWARE. HARDWARE. INTELLIGENCE.</h1></div><div className="heroSide"><p>Our technology stack is selected around the product: AI when reasoning matters, edge and hardware when proximity matters, cloud when scale matters, and security everywhere.</p></div></section>
<section className="contentGrid shell"><div><p className="eyebrow">STACK</p><h2>Built as an ecosystem.</h2></div><div className="cardGrid"><article><span>01</span><h3>Artificial Intelligence</h3><p>Agentic systems, model-enabled applications, retrieval and secure AI workflows.</p></article><article><span>02</span><h3>Cloud & APIs</h3><p>Modern infrastructure, data services and integrations for resilient products.</p></article><article><span>03</span><h3>Cybersecurity</h3><p>Secure software engineering, monitoring, telemetry and defensive controls.</p></article><article><span>04</span><h3>Edge & Hardware</h3><p>Connected devices, portable appliances and local processing when cloud-only is not enough.</p></article></div></section>
<section className="contentGrid shell"><div><Status>HARDWARE DEVELOPMENT</Status><h2>Designed for physical products too.</h2></div><div><p>The site architecture now supports future cybersecurity appliances and experimental hardware with product status, specifications, interactive presentation and eventual preorder or purchase flows when appropriate.</p><div className="specTable"><div className="specRow"><span>Future device classes</span><span>Travel security gateways, network monitors, USB security scanners, incident-response devices, IoT/OT monitoring</span></div><div className="specRow"><span>Presentation</span><span>3D rotation, zoom, exploded component views and technical specifications</span></div><div className="specRow"><span>Operating principle</span><span>Defensive security and authorized testing only</span></div></div></div></section>
</PageShell>}
